# Blitzwolf BW-RC1 IR Controller

substitutions:
  device_id: !secret esp_blitzwolf_bw_rc1_01_device_id
  device_name: !secret esp_blitzwolf_bw_rc1_01_device_name

  api_password: !secret esp_api_password
  ota_password: !secret esp_ota_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  ir_receiver_pin: GPIO05 # IR Receiver
  ir_transmitter_pin: GPIO14 # IR Transmitter
  restart_button_pin: GPIO13 # Button
  status_led_pin: GPIO04 # Blue LED

esphome:
  name: ${device_id}

  <<: !include common/board/esp8266.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/status_led.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/restart_button.yaml

remote_receiver:
  - !include common/remote_receiver/ir_receiver.yaml

remote_transmitter:
  - !include common/remote_transmitter/ir_transmitter.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml

switch:
  - !include common/switch/restart.yaml
