# Gosund SP111 Power Monitoring Plug

substitutions:
  device_id: !secret esp_gosund_sp111_01_device_id
  device_name: !secret esp_gosund_sp111_01_device_name

  api_password: !secret esp_api_password
  ota_password: !secret esp_ota_password
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  button_pin: GPIO13 # Power Button
  status_led_pin: GPIO00 # Red LED
  power_cf_pin: GPIO5 # Powermeter
  power_cf1_pin: GPIO14 # Powermeter
  power_sel_pin: GPIO12 # Powermeter
  relay_pin: GPIO15 # Relay

  current_resistor: '0.001' # Powermeter Current Resistor
  voltage_divider: '910' # Powermeter Voltage Devider

esphome:
  name: ${device_id}

  <<: !include common/board/esp8266.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/status_led.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/power_button.yaml

sensor:
  - !include common/sensor/hlw8012.yaml
  - !include common/sensor/total_daily_energy.yaml
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml

switch:
  - !include common/switch/relay.yaml
  - !include common/switch/restart.yaml



