# Gosund SP111 Power Monitoring Plug
substitutions:
  device_id: !secret esp_gosund_sp111_01_device_id
  device_name: !secret esp_gosund_sp111_01_device_name

  api_password: !secret esp_api_password
  ota_password: !secret esp_ota_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  button_pin: GPIO13 # Power Button
  status_led_pin: GPIO00 # Red LED
  power_cf_pin: GPIO5 # Powermeter
  power_cf1_pin: GPIO14 # Powermeter
  power_sel_pin: GPIO12 # Powermeter
  relay_pin: GPIO15 # Relay

  current_resistor: '0.001' # Powermeter Current Resistor
  voltage_divider: '910' # Powermeter Voltage Devider


esphome:
  name: ${device_id}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: True

api:
  password: ${api_password}

ota:
  password: ${ota_password}

time:
  platform: homeassistant
  id: homeassistant_time

web_server:
  port: 80

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${device_name} AP"
    password: ${wifi_password}

captive_portal:
logger:


binary_sensor:
  - platform: gpio
    id: power_button
    pin:
      number: ${button_pin}
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay
    filters:
      - delayed_on: 10ms

  - platform: status
    name: "${device_name} Status"

sensor:
  - platform: hlw8012
    sel_pin:
      number: ${power_sel_pin}
      inverted: True
    cf_pin: ${power_cf_pin}
    cf1_pin: ${power_cf1_pin}
    current:
      name: "${device_name} Current"
    power:
      name: "${device_name} Power"
      id: power_monitor_value
      filters:
        - lambda: return (x / 2.2);
    voltage:
      name: "${device_name} Voltage"
    current_resistor: ${current_resistor} # default 0.001
    voltage_divider: ${voltage_divider} # default 2351
    change_mode_every: 3 # default 8
    update_interval: 10s # default 60s

  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy"
    power_id: power_monitor_value
    unit_of_measurement: kW
    filters:
      - multiply: 0.001

  - platform: uptime
    name: "${device_name} Uptime"

  - platform: wifi_signal
    name: "${device_name} Wifi Signal"
    update_interval: 60s

status_led:
  pin:
    number: ${status_led_pin}
    inverted: True

switch:
  - platform: gpio
    name:   ${device_name}
    id: relay
    pin: $relay_pin
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: restart
    name: ${device_name} Restart
