# Koogeek KLOE4 Power Strip

substitutions:
  device_id: !secret esp_koogeek_kloe4_01_device_id
  device_name: !secret esp_koogeek_kloe4_01_device_name

  api_password: !secret esp_api_password
  ota_password: !secret esp_ota_password
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  button_pin: GPIO03 # Power Button
  status_led_pin: GPIO1 # Green LED
  relay_1_pin: GPIO05 # Relay 1
  relay_2_pin: GPIO04 # Relay 2
  relay_3_pin: GPIO12 # Relay 3
  relay_4_pin: GPIO13 # Relay 4
  relay_5_pin: GPIO14 # Relay 5

esphome:
  name: ${device_id}

  <<: !include common/board/esp8266.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/status_led.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/power_button.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml

switch:
  - !include common/switch/restart.yaml

  - platform: gpio
    name: ${device_name} 1
    id: relay
    pin: ${relay_1_pin}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: ${device_name} 2
    id: relay_2
    pin: ${relay_2_pin}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: ${device_name} 3
    id: relay_3
    pin: ${relay_3_pin}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: ${device_name} 4
    id: relay_4
    pin: ${relay_4_pin}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: ${device_name} 5
    id: relay_5
    pin: ${relay_5_pin}
    restore_mode: RESTORE_DEFAULT_OFF
