# Room Sensor

substitutions:
  device_id: !secret esp_room_sensor_01_device_id
  device_name: !secret esp_room_sensor_01_device_name

  api_encryption_key: !secret esp_api_encryption_key
  ota_password: !secret esp_ota_password
  syslog_ip_address: !secret syslog_ip_address
  syslog_port: !secret syslog_port
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  i2c_scl_pin: GPIO05 # I2C Clock
  i2c_sda_pin: GPIO04 # I2C Data
  illuminance_pin: GPIO36 # ADC
  motion_pin: GPIO14

  bme280_address: '0x76'
  homeassistant_ble_gateway_devices_attribute: 'devices'
  homeassistant_ble_gateway_devices_entity_id: 'binary_sensor.ble_gateway'
  homeassistant_ble_gateway_discovery_attribute: 'discovery'
  homeassistant_ble_gateway_discovery_entity_id: 'binary_sensor.ble_gateway'

external_components:
  - !include common/external_components/ble_gateway.yaml
  - !include common/external_components/syslog.yaml

esphome:
  name: ${device_id}

  <<: !include common/board/esp32.yaml

<<: !include common/api.yaml
<<: !include common/ble_gateway.yaml
<<: !include common/bluetooth_proxy.yaml
<<: !include common/i2c.yaml
<<: !include common/ota.yaml
<<: !include common/syslog.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

esp32_ble_tracker:
logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/homeassistant_ble_gateway_discovery.yaml
  - !include common/binary_sensor/motion.yaml #AM312

sensor:
  - !include common/sensor/bme280.yaml #BME280
  - !include common/sensor/illuminance.yaml #TEMT6000
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml

switch:
  - !include common/switch/ble_gateway_discovery.yaml
  - !include common/switch/restart.yaml

text_sensor:
  - !include common/text_sensor/homeassistant_ble_gateway_devices.yaml

