# Room Sensor

substitutions:
  device_id: !secret esp_room_sensor_01_device_id
  device_name: !secret esp_room_sensor_01_device_name

  api_password: !secret esp_api_password
  ota_password: !secret esp_ota_password
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  i2c_scl_pin: GPIO05 # I2C Clock
  i2c_sda_pin: GPIO04 # I2C Data
  illuminance_pin: GPIO36 # ADC
  motion_pin: GPIO14

  bme280_address: '0x76'
  miband_mac_address: !secret miband_mac_address

esphome:
  name: ${device_id}

  <<: !include common/board/esp32.yaml

<<: !include common/api.yaml
<<: !include common/i2c.yaml
<<: !include common/ota.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

esp32_ble_tracker:
logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/miband.yaml
  - !include common/binary_sensor/motion.yaml #AM312

sensor:
  - !include common/sensor/bme280.yaml #BME280
  - !include common/sensor/illuminance.yaml #TEMT6000
  - !include common/sensor/miband_rssi.yaml
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml

switch:
  - !include common/switch/restart.yaml
