# Shelly 2.5 Power Monitoring Relay Light

substitutions:
  device_id: !secret esp_shelly_2_5_light_01_device_id
  device_name: !secret esp_shelly_2_5_light_01_device_name

  api_password: !secret esp_api_password
  ota_password: !secret esp_ota_password
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  i2c_scl_pin: GPIO14 # I2C Clock
  i2c_sda_pin: GPIO12 # I2C Data
  input1_pin: GPIO13 # Switch 1
  input2_pin: GPIO05 # Switch 2
  relay1_pin: GPIO04 # Relay 1
  relay2_pin: GPIO15 # Relay 2
  restart_button_pin: GPIO13 # Restart Button
  status_led_pin: GPIO00 # Red LED
  temperature_analog_pin: A0 # Temperature Analog Reading

  ntc_b_constant: '3350'
  ntc_reference_resistance: 10kOhm
  ntc_reference_temperature: 298.15K
  temperature_resistance_resistor: 32kOhm

esphome:
  name: ${device_id}

  <<: !include common/board/esp8266.yaml

<<: !include common/api.yaml
<<: !include common/i2c.yaml
<<: !include common/ota.yaml
<<: !include common/status_led.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/restart_button.yaml
  - platform: gpio
    id: input1
    pin:
      number: $input1_pin
    on_state:
      then:
        - light.toggle: light1
  - platform: gpio
    id: input2
    pin:
      number: $input2_pin
    on_state:
      then:
        - light.toggle: light2

light:
  - platform: binary
    name: "${device_name} Light 1"
    id: light1
    output: relay1
  - platform: binary
    name: "${device_name} Light 2"
    id: light2
    output: relay2

output:
  - platform: gpio
    pin: $relay1_pin
    id: relay1
  - platform: gpio
    pin: $relay2_pin
    id: relay2

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml
  - !include common/sensor/ade7953.yaml
  - !include common/sensor/ntc.yaml
  - !include common/sensor/temperature_analog.yaml
  - !include common/sensor/temperature_resistance.yaml
  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy 1"
    power_id: power_monitor_value_1
    unit_of_measurement: "kW"
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy 2"
    power_id: power_monitor_value_2
    unit_of_measurement: "kW"
    filters:
      - multiply: 0.001

switch:
  - !include common/switch/restart.yaml
