# Shelly 2.5 Power Monitoring Relay Light

substitutions:
  device_id: !secret esp_shelly_2_5_light_01_device_id
  device_name: !secret esp_shelly_2_5_light_01_device_name

  api_encryption_key: !secret esp_api_encryption_key
  ota_password: !secret esp_ota_password
  syslog_ip_address: !secret syslog_ip_address
  syslog_port: !secret syslog_port
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  i2c_scl_pin: GPIO14 # I2C Clock
  i2c_sda_pin: GPIO12 # I2C Data
  input_1_pin: GPIO13 # Switch 1
  input_2_pin: GPIO05 # Switch 2
  relay_1_pin: GPIO04 # Relay 1
  relay_2_pin: GPIO15 # Relay 2
  restart_button_pin: GPIO13 # Restart Button
  status_led_pin: GPIO00 # Red LED
  temperature_analog_pin: A0 # Temperature Analog Reading

  ntc_b_constant: '3350'
  ntc_reference_resistance: 10kOhm
  ntc_reference_temperature: 298.15K
  temperature_resistance_resistor: 32kOhm

external_components:
  - !include common/external_components/syslog.yaml

esphome:
  name: ${device_id}

  <<: !include common/board/esp8266.yaml

<<: !include common/api.yaml
<<: !include common/i2c.yaml
<<: !include common/ota.yaml
<<: !include common/status_led.yaml
<<: !include common/syslog.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/restart_button.yaml
  - platform: gpio
    id: input_1
    pin:
      number: ${input_1_pin}
    on_state:
      then:
        - light.toggle: light_1
  - platform: gpio
    id: input_2
    pin:
      number: ${input_2_pin}
    on_state:
      then:
        - light.toggle: light_2

light:
  - platform: binary
    name: "${device_name} Light 1"
    id: light_1
    output: relay_1
  - platform: binary
    name: "${device_name} Light 2"
    id: light_2
    output: relay_2

output:
  - platform: gpio
    pin: ${relay_1_pin}
    id: relay_1
  - platform: gpio
    pin: ${relay_2_pin}
    id: relay_2

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml
  - !include common/sensor/ade7953.yaml
  - !include common/sensor/ntc.yaml
  - !include common/sensor/temperature_analog.yaml
  - !include common/sensor/temperature_resistance.yaml
  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy 1"
    power_id: power_monitor_value_1
    unit_of_measurement: "kW"
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy 2"
    power_id: power_monitor_value_2
    unit_of_measurement: "kW"
    filters:
      - multiply: 0.001

switch:
  - !include common/switch/restart.yaml
