# Sonoff Basic Relay

substitutions:
  device_id: !secret esp_sonoff_basic_01_device_id
  device_name: !secret esp_sonoff_basic_01_device_name

  api_encryption_key: !secret esp_api_encryption_key
  ota_password: !secret esp_ota_password
  syslog_ip_address: !secret syslog_ip_address
  syslog_port: !secret syslog_port
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  button_pin: GPIO00 # Power Button
  status_led_pin: GPIO13 # Green LED
  relay_pin: GPIO12 # Relay

external_components:
  - !include common/external_components/syslog.yaml

esphome:
  name: ${device_id}

  <<: !include common/board/esp8266.yaml

<<: !include common/api.yaml
<<: !include common/logger.yaml
<<: !include common/ota.yaml
<<: !include common/status_led.yaml
<<: !include common/syslog.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/power_button.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml

switch:
  - !include common/switch/relay.yaml
  - !include common/switch/restart.yaml
