# Ventilation
#
# Sonoff TH10 Relay with Temperature/Humidity Sensor

substitutions:
  device_id: !secret esp_ventilation_device_id
  device_name: !secret esp_ventilation_device_name

  api_password: !secret esp_api_password
  ota_password: !secret esp_ota_password
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  button_pin: GPIO00 # Power Button
  dht_pin: GPIO14
  status_led_pin: GPIO13 # Green LED
  relay_pin: GPIO12 # Relay

  dht_model: SI7021 # Default AUTO_DETECT
  dht_update_interval: 60s # Default 60s
  humidity_treshold_off: '75.0'
  humidity_treshold_on: '80.0'

esphome:
  name: ${device_id}
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/status_led.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

logger:

binary_sensor:
  - !include common/binary_sensor/device_status.yaml
  - !include common/binary_sensor/power_button.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml
  - platform: dht
    pin: $dht_pin
    model: $dht_model
    update_interval: $dht_update_interval
    temperature:
      name: "${device_name} Temperature"
    humidity:
      name: "${device_name} Humidity"
      on_value_range:
        - above: $humidity_treshold_on
          then:
            - switch.turn_on: relay
        - below: $humidity_treshold_off
          then:
            - switch.turn_off: relay


switch:
  - !include common/switch/relay.yaml
  - !include common/switch/restart.yaml
