# DIY Hue Light (adressable)

substitutions:
  device_id: !secret esp_yeelight_yltd003_01_device_id
  device_name: !secret esp_yeelight_yltd003_01_device_name

  api_encryption_key: !secret esp_api_encryption_key
  ota_password: !secret esp_ota_password
  syslog_ip_address: !secret syslog_ip_address
  syslog_port: !secret syslog_port
  wifi_domain: !secret wifi_domain
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  data_pin: GPIO13
  output_cw_pin: GPIO12
  output_ww_pin: GPIO5
  power_supply_pin: GPIO4

  chipset: WS2812
  color_correct_r: 95%
  color_correct_g: 95%
  color_correct_b: 95%
  constant_brightness: 'true'
  cold_white_color_temperature: '6500 K' # Default '6500 K'
  warm_white_color_temperature: '2700 K' # Default '2700 K'
  default_transition_length: 1s # Default 1s
  gamma_correct: '2.8' # Default 2.8
  num_leds: '40'
  restore_mode: RESTORE_DEFAULT_OFF
  rgb_order: GRB

external_components:
  - !include common/external_components/ddp.yaml
  - !include common/external_components/syslog.yaml

esphome:
  name: ${device_id}

esp8266:
  board: esp_wroom_02
  restore_from_flash: True

<<: !include common/api.yaml
<<: !include common/logger.yaml
<<: !include common/ota.yaml
<<: !include common/power_supply.yaml
<<: !include common/syslog.yaml
<<: !include common/time.yaml
<<: !include common/webserver.yaml
<<: !include common/wifi.yaml

ddp:
wled:

e131:
  method: multicast

binary_sensor:
  - !include common/binary_sensor/device_status.yaml

light:
  - !include common/light/cwww.yaml
  - !include common/light/neopixelbus_psu.yaml

output:
  - platform: esp8266_pwm
    pin: ${output_cw_pin}
    id: output_cw
    power_supply: power
  - platform: esp8266_pwm
    pin: ${output_ww_pin}
    id: output_ww
    power_supply: power

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi_signal.yaml

text_sensor:
  - !include common/text_sensor/light_id.yaml

switch:
  - !include common/switch/restart.yaml
